// flow-typed signature: 544214d0caaf428126ec429b9ec87727
// flow-typed version: <<STUB>>/@react-corekit/use-interval_v^1.1.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-corekit/use-interval'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-corekit/use-interval' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-corekit/use-interval/dist/index.es' {
  declare module.exports: any;
}

declare module '@react-corekit/use-interval/dist' {
  declare module.exports: any;
}

declare module '@react-corekit/use-interval/example/src/App' {
  declare module.exports: any;
}

declare module '@react-corekit/use-interval/example/src' {
  declare module.exports: any;
}

declare module '@react-corekit/use-interval/rollup.config' {
  declare module.exports: any;
}

declare module '@react-corekit/use-interval/src' {
  declare module.exports: any;
}

declare module '@react-corekit/use-interval/src/test' {
  declare module.exports: any;
}

declare module '@react-corekit/use-interval/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-corekit/use-interval/dist/index.es.js' {
  declare module.exports: $Exports<'@react-corekit/use-interval/dist/index.es'>;
}
declare module '@react-corekit/use-interval/dist/index' {
  declare module.exports: $Exports<'@react-corekit/use-interval/dist'>;
}
declare module '@react-corekit/use-interval/dist/index.js' {
  declare module.exports: $Exports<'@react-corekit/use-interval/dist'>;
}
declare module '@react-corekit/use-interval/example/src/App.js' {
  declare module.exports: $Exports<'@react-corekit/use-interval/example/src/App'>;
}
declare module '@react-corekit/use-interval/example/src/index' {
  declare module.exports: $Exports<'@react-corekit/use-interval/example/src'>;
}
declare module '@react-corekit/use-interval/example/src/index.js' {
  declare module.exports: $Exports<'@react-corekit/use-interval/example/src'>;
}
declare module '@react-corekit/use-interval/rollup.config.js' {
  declare module.exports: $Exports<'@react-corekit/use-interval/rollup.config'>;
}
declare module '@react-corekit/use-interval/src/index' {
  declare module.exports: $Exports<'@react-corekit/use-interval/src'>;
}
declare module '@react-corekit/use-interval/src/index.js' {
  declare module.exports: $Exports<'@react-corekit/use-interval/src'>;
}
declare module '@react-corekit/use-interval/src/test.js' {
  declare module.exports: $Exports<'@react-corekit/use-interval/src/test'>;
}
declare module '@react-corekit/use-interval/test/index' {
  declare module.exports: $Exports<'@react-corekit/use-interval/test'>;
}
declare module '@react-corekit/use-interval/test/index.js' {
  declare module.exports: $Exports<'@react-corekit/use-interval/test'>;
}
