// flow-typed signature: 3da5c920979c3598de2465ef0342cb80
// flow-typed version: <<STUB>>/electron-debug_v3.0.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-debug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-debug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-debug/index' {
  declare module.exports: $Exports<'electron-debug'>;
}
declare module 'electron-debug/index.js' {
  declare module.exports: $Exports<'electron-debug'>;
}
