// flow-typed signature: aa75e0ae7701c6ba059dd8ae2b4a5901
// flow-typed version: <<STUB>>/eslint-plugin-import_v2.20.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-import/config/electron' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/config/errors' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/config/react-native' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/config/react' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/config/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/config/stage-0' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/config/typescript' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/config/warnings' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/core/importType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/core/staticRequire' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/docsUrl' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/ExportMap' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/importDeclaration' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/default' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/dynamic-import-chunkname' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/export' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/exports-last' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/extensions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/first' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/group-exports' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/imports-first' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/max-dependencies' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/named' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/namespace' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/newline-after-import' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-absolute-path' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-amd' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-anonymous-default-export' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-commonjs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-cycle' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-default-export' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-deprecated' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-duplicates' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-dynamic-require' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-extraneous-dependencies' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-internal-modules' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-mutable-exports' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-named-as-default-member' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-named-as-default' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-named-default' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-named-export' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-namespace' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-nodejs-modules' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-relative-parent-imports' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-restricted-paths' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-self-import' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-unassigned-import' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-unresolved' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-unused-modules' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-useless-path-segments' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/no-webpack-loader-syntax' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/order' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/prefer-default-export' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/lib/rules/unambiguous' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/debug/karma.conf' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/debug/node' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/debug/src/browser' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/debug/src/debug' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/debug/src' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/debug/src/inspector-log' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/debug/src/node' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/declaredScope' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/hash' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/ignore' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/module-require' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/ModuleCache' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/moduleVisitor' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/parse' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/resolve' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/unambiguous' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/find-up' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/locate-path' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/ms' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/p-limit' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/p-locate' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/p-try' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/path-exists' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/node_modules/pkg-dir' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-import/config/electron.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/electron'>;
}
declare module 'eslint-plugin-import/config/errors.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/errors'>;
}
declare module 'eslint-plugin-import/config/react-native.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/react-native'>;
}
declare module 'eslint-plugin-import/config/react.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/react'>;
}
declare module 'eslint-plugin-import/config/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/recommended'>;
}
declare module 'eslint-plugin-import/config/stage-0.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/stage-0'>;
}
declare module 'eslint-plugin-import/config/typescript.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/typescript'>;
}
declare module 'eslint-plugin-import/config/warnings.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/warnings'>;
}
declare module 'eslint-plugin-import/lib/core/importType.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/core/importType'>;
}
declare module 'eslint-plugin-import/lib/core/staticRequire.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/core/staticRequire'>;
}
declare module 'eslint-plugin-import/lib/docsUrl.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/docsUrl'>;
}
declare module 'eslint-plugin-import/lib/ExportMap.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/ExportMap'>;
}
declare module 'eslint-plugin-import/lib/importDeclaration.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/importDeclaration'>;
}
declare module 'eslint-plugin-import/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-import/lib'>;
}
declare module 'eslint-plugin-import/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib'>;
}
declare module 'eslint-plugin-import/lib/rules/default.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/default'>;
}
declare module 'eslint-plugin-import/lib/rules/dynamic-import-chunkname.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/dynamic-import-chunkname'>;
}
declare module 'eslint-plugin-import/lib/rules/export.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/export'>;
}
declare module 'eslint-plugin-import/lib/rules/exports-last.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/exports-last'>;
}
declare module 'eslint-plugin-import/lib/rules/extensions.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/extensions'>;
}
declare module 'eslint-plugin-import/lib/rules/first.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/first'>;
}
declare module 'eslint-plugin-import/lib/rules/group-exports.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/group-exports'>;
}
declare module 'eslint-plugin-import/lib/rules/imports-first.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/imports-first'>;
}
declare module 'eslint-plugin-import/lib/rules/max-dependencies.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/max-dependencies'>;
}
declare module 'eslint-plugin-import/lib/rules/named.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/named'>;
}
declare module 'eslint-plugin-import/lib/rules/namespace.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/namespace'>;
}
declare module 'eslint-plugin-import/lib/rules/newline-after-import.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/newline-after-import'>;
}
declare module 'eslint-plugin-import/lib/rules/no-absolute-path.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-absolute-path'>;
}
declare module 'eslint-plugin-import/lib/rules/no-amd.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-amd'>;
}
declare module 'eslint-plugin-import/lib/rules/no-anonymous-default-export.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-anonymous-default-export'>;
}
declare module 'eslint-plugin-import/lib/rules/no-commonjs.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-commonjs'>;
}
declare module 'eslint-plugin-import/lib/rules/no-cycle.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-cycle'>;
}
declare module 'eslint-plugin-import/lib/rules/no-default-export.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-default-export'>;
}
declare module 'eslint-plugin-import/lib/rules/no-deprecated.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-deprecated'>;
}
declare module 'eslint-plugin-import/lib/rules/no-duplicates.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-duplicates'>;
}
declare module 'eslint-plugin-import/lib/rules/no-dynamic-require.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-dynamic-require'>;
}
declare module 'eslint-plugin-import/lib/rules/no-extraneous-dependencies.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-extraneous-dependencies'>;
}
declare module 'eslint-plugin-import/lib/rules/no-internal-modules.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-internal-modules'>;
}
declare module 'eslint-plugin-import/lib/rules/no-mutable-exports.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-mutable-exports'>;
}
declare module 'eslint-plugin-import/lib/rules/no-named-as-default-member.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-named-as-default-member'>;
}
declare module 'eslint-plugin-import/lib/rules/no-named-as-default.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-named-as-default'>;
}
declare module 'eslint-plugin-import/lib/rules/no-named-default.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-named-default'>;
}
declare module 'eslint-plugin-import/lib/rules/no-named-export.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-named-export'>;
}
declare module 'eslint-plugin-import/lib/rules/no-namespace.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-namespace'>;
}
declare module 'eslint-plugin-import/lib/rules/no-nodejs-modules.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-nodejs-modules'>;
}
declare module 'eslint-plugin-import/lib/rules/no-relative-parent-imports.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-relative-parent-imports'>;
}
declare module 'eslint-plugin-import/lib/rules/no-restricted-paths.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-restricted-paths'>;
}
declare module 'eslint-plugin-import/lib/rules/no-self-import.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-self-import'>;
}
declare module 'eslint-plugin-import/lib/rules/no-unassigned-import.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-unassigned-import'>;
}
declare module 'eslint-plugin-import/lib/rules/no-unresolved.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-unresolved'>;
}
declare module 'eslint-plugin-import/lib/rules/no-unused-modules.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-unused-modules'>;
}
declare module 'eslint-plugin-import/lib/rules/no-useless-path-segments.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-useless-path-segments'>;
}
declare module 'eslint-plugin-import/lib/rules/no-webpack-loader-syntax.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/no-webpack-loader-syntax'>;
}
declare module 'eslint-plugin-import/lib/rules/order.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/order'>;
}
declare module 'eslint-plugin-import/lib/rules/prefer-default-export.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/prefer-default-export'>;
}
declare module 'eslint-plugin-import/lib/rules/unambiguous.js' {
  declare module.exports: $Exports<'eslint-plugin-import/lib/rules/unambiguous'>;
}
declare module 'eslint-plugin-import/memo-parser/index' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser'>;
}
declare module 'eslint-plugin-import/memo-parser/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/debug/karma.conf.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/debug/karma.conf'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/debug/node.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/debug/node'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/debug/src/browser.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/debug/src/browser'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/debug/src/debug.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/debug/src/debug'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/debug/src/index' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/debug/src'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/debug/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/debug/src'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/debug/src/inspector-log.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/debug/src/inspector-log'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/debug/src/node.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/debug/src/node'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/declaredScope.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/declaredScope'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/hash.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/hash'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/ignore.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/ignore'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/module-require.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/module-require'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/ModuleCache.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/ModuleCache'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/moduleVisitor.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/moduleVisitor'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/parse.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/parse'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/resolve.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/resolve'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/unambiguous.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/eslint-module-utils/unambiguous'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/find-up/index' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/find-up'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/find-up/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/find-up'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/locate-path/index' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/locate-path'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/locate-path/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/locate-path'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/ms/index' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/ms'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/ms/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/ms'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/p-limit/index' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/p-limit'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/p-limit/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/p-limit'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/p-locate/index' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/p-locate'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/p-locate/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/p-locate'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/p-try/index' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/p-try'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/p-try/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/p-try'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/path-exists/index' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/path-exists'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/path-exists/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/path-exists'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/pkg-dir/index' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/pkg-dir'>;
}
declare module 'eslint-plugin-import/memo-parser/node_modules/pkg-dir/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/node_modules/pkg-dir'>;
}
