// flow-typed signature: e02f4132faae0b7cc4136f97d39f8c03
// flow-typed version: <<STUB>>/fix-path_v2.1.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fix-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fix-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fix-path/index' {
  declare module.exports: $Exports<'fix-path'>;
}
declare module 'fix-path/index.js' {
  declare module.exports: $Exports<'fix-path'>;
}
