// flow-typed signature: 1325b45d32be542e5ab93c139e963e30
// flow-typed version: <<STUB>>/hosts-so-easy_v1.2.8/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hosts-so-easy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hosts-so-easy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hosts-so-easy/lib' {
  declare module.exports: any;
}

declare module 'hosts-so-easy/lib/index.spec' {
  declare module.exports: any;
}

declare module 'hosts-so-easy/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hosts-so-easy/lib/index' {
  declare module.exports: $Exports<'hosts-so-easy/lib'>;
}
declare module 'hosts-so-easy/lib/index.js' {
  declare module.exports: $Exports<'hosts-so-easy/lib'>;
}
declare module 'hosts-so-easy/lib/index.spec.js' {
  declare module.exports: $Exports<'hosts-so-easy/lib/index.spec'>;
}
declare module 'hosts-so-easy/wallaby.js' {
  declare module.exports: $Exports<'hosts-so-easy/wallaby'>;
}
