// flow-typed signature: fab8f5eff06ac2d2aadf9f11a25506de
// flow-typed version: <<STUB>>/i18next-electron-fs-backend_v1.1.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-electron-fs-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-electron-fs-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18next-electron-fs-backend/lib' {
  declare module.exports: any;
}

declare module 'i18next-electron-fs-backend/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18next-electron-fs-backend/lib/index' {
  declare module.exports: $Exports<'i18next-electron-fs-backend/lib'>;
}
declare module 'i18next-electron-fs-backend/lib/index.js' {
  declare module.exports: $Exports<'i18next-electron-fs-backend/lib'>;
}
declare module 'i18next-electron-fs-backend/lib/utils.js' {
  declare module.exports: $Exports<'i18next-electron-fs-backend/lib/utils'>;
}
