// flow-typed signature: 3697b76439adbe86c4fe9dee860b24a3
// flow-typed version: <<STUB>>/opener_v1.5.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opener'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opener' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'opener/bin/opener-bin' {
  declare module.exports: any;
}

declare module 'opener/lib/opener' {
  declare module.exports: any;
}

// Filename aliases
declare module 'opener/bin/opener-bin.js' {
  declare module.exports: $Exports<'opener/bin/opener-bin'>;
}
declare module 'opener/lib/opener.js' {
  declare module.exports: $Exports<'opener/lib/opener'>;
}
