// flow-typed signature: 6e4c79b36b9455057200fc78369d8230
// flow-typed version: <<STUB>>/retriable-download_v3.0.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retriable-download'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retriable-download' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'retriable-download/src' {
  declare module.exports: any;
}

declare module 'retriable-download/test/00_test' {
  declare module.exports: any;
}

declare module 'retriable-download/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'retriable-download/src/index' {
  declare module.exports: $Exports<'retriable-download/src'>;
}
declare module 'retriable-download/src/index.js' {
  declare module.exports: $Exports<'retriable-download/src'>;
}
declare module 'retriable-download/test/00_test.js' {
  declare module.exports: $Exports<'retriable-download/test/00_test'>;
}
declare module 'retriable-download/test/index' {
  declare module.exports: $Exports<'retriable-download/test'>;
}
declare module 'retriable-download/test/index.js' {
  declare module.exports: $Exports<'retriable-download/test'>;
}
