// flow-typed signature: e2c39cdfa731d0c5ba404bdc8e21a34c
// flow-typed version: <<STUB>>/ssl-root-cas_v1.3.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ssl-root-cas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ssl-root-cas' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ssl-root-cas/ca-store-generator' {
  declare module.exports: any;
}

declare module 'ssl-root-cas/latest' {
  declare module.exports: any;
}

declare module 'ssl-root-cas/ssl-root-cas-latest' {
  declare module.exports: any;
}

declare module 'ssl-root-cas/ssl-root-cas' {
  declare module.exports: any;
}

declare module 'ssl-root-cas/ssl-root-cas.tpl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ssl-root-cas/ca-store-generator.js' {
  declare module.exports: $Exports<'ssl-root-cas/ca-store-generator'>;
}
declare module 'ssl-root-cas/latest.js' {
  declare module.exports: $Exports<'ssl-root-cas/latest'>;
}
declare module 'ssl-root-cas/ssl-root-cas-latest.js' {
  declare module.exports: $Exports<'ssl-root-cas/ssl-root-cas-latest'>;
}
declare module 'ssl-root-cas/ssl-root-cas.js' {
  declare module.exports: $Exports<'ssl-root-cas/ssl-root-cas'>;
}
declare module 'ssl-root-cas/ssl-root-cas.tpl.js' {
  declare module.exports: $Exports<'ssl-root-cas/ssl-root-cas.tpl'>;
}
